apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: hello
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nodejs-http-server
          image: cannin/nodejs-http-server
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
