apiVersion: v1
kind: Pod
metadata:
  name: simple
spec:
  containers:
    - name: simple
      image: docker.io/grafana/k6
      args:
      - run
      - /m/simple.js
      volumeMounts:
      - name: simple
        mountPath: /m
  volumes:
    - name: simple
      configMap:
        name: simple
