apiVersion: v1
kind: Pod
metadata:
  name: k6pod
spec:
  containers:
    - name: load
      image: docker.io/grafana/k6
      args:
      - run
      - /m/load.js
      volumeMounts:
      - name: load
        mountPath: /m
  volumes:
    - name: load
      configMap:
        name: load
